# Generated by Django 6.1.1 on 2026-10-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_qrcodetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='national_id_hash',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
