# Generated by Django 6.1.1 on 2026-10-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member_national_id_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='national_id_encrypted',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
